### ISSUE TITLE
Write a fix for the logout route in the 'User' controller

### ISSUE THREAD

**Issue by FaizanAhmedSP707** [TomStrong/DevOpsAssessment#31]
Problem
======
There is an error in the file called 'user.controller.js' which is located in server/controllers, where the catch block has 'logut' instead of 'logout'. Below is the code snippet:

--------------------------------------
Code Snippet
=========

`
try {
        req.session.destroy();
        global.user = false;
        res.redirect('/');
    } catch (e) {
        if (e.errors) {
            console.log(e.errors);
            res.render('/logut', { errors: e.errors });
            return;
        }
        return res.status(400).send({
            message: JSON.parse(e),
        });
    }
`

(I tried using Markdown to make it look prettier, but the code snippet looks terrible here)
Also, it would be helpful to completely review all of the routes to make sure it works(like the re-directs), as I believe @Joao-Potes wrote this but I'm not sure.

----------

Summary
======
@TomStrong, please have a look and assign the relevant team member for this so that a fix can be pushed out, after which I can pull the changes and work on testing the user routes properly. I'll add the bug labels myself.

**Comment by FaizanAhmedSP707** [comment]
Please comment if you have received it. Thanks.

**Comment by TomStrong** [comment]
I'll look at this tomorrow
