### ISSUE TITLE
Fix uncaught error on the Home page which relates to POIs

### ISSUE THREAD

**Issue by FaizanAhmedSP707** [TomStrong/DevOpsAssessment#47]
Problem Description
=====
There seems to be an uncaught error in the JS file that the home page uses to carry out the associated functionalities associated with the home page. This error relates to the table being generated to show POIs from a certain region, where the variable being used to hold the list of POIs is not a JavaScript array, and thus '.forEach' cannot be used on this array.

Analysis of error and possible fix
==========
The variable holding the list of POIs is actually a JSON array, which usually requires a regular for loop to loop through all elements in the array. Either a for loop should be used, or if the results returned from MongoDB is actually a JavaScript array, then there is no need to convert it to JSON when a response is received from the database.

Screenshots (of issue)
==============
![image](https://github.com/TomStrong/DevOpsAssessment/assets/91551587/60a8347d-63ce-4257-8c3e-b2b9541ebee0)

![image](https://github.com/TomStrong/DevOpsAssessment/assets/91551587/5ffaf23e-b7bd-4fec-8864-fe53b27f1f0e)
(when the data is received back from the database)

![image](https://github.com/TomStrong/DevOpsAssessment/assets/91551587/41b407bb-eb6d-4728-ae7f-0ad7b04e1858)
(where the error occurs)

Any further comments
===============
There is not much else to add, except that this issue shouldn't be too difficult to fix, please make a branch/make a pull request for this issue. Thanks.

**Comment by TomStrong** [comment]
This is caused by the NGINX proxy issue, the API route sometimes returns an error instead of an array.
![image](https://github.com/TomStrong/DevOpsAssessment/assets/72138672/40146e16-f3fb-4a61-96b5-a9d14efd5be1)
However, there should be client side error handling for all API calls to ensure that an appropriate error is displayed if the API sends back an error.

**Comment by ali1373107** [comment]
changes to the APIs makes this irrelevant

**Comment by ali1373107** [comment]
changes to the APIs makes this irrelevant
