### ISSUE TITLE
Install Docker on remote VM

### ISSUE THREAD

**Issue by TomStrong** [TomStrong/DevOpsAssessment#5]

**Comment by FaizanAhmedSP707** [comment]
Hey @TomStrong, let me know if this actually has been completed so that I can mark it as complete and close this issue.

Thanks,
FaizanAhmedSP707

**Comment by TomStrong** [comment]
@FaizanAhmedSP707 yes, both tasks in done are complete

**Comment by FaizanAhmedSP707** [comment]
Thanks for letting me know, I will close this issue now.

**Comment by FaizanAhmedSP707** [comment]
Done with this task for the project.
