### ISSUE TITLE
Research using Azure Blob to store photos

### ISSUE THREAD

**Issue by 5thaks07** [TomStrong/DevOpsAssessment#59]

**Comment by TomStrong** [comment]
https://www.npmjs.com/package/@azure/storage-blob

**Comment by TomStrong** [comment]
We shouldn't have any funding issues for using Azure Blob storage


![Image](https://github.com/TomStrong/DevOpsAssessment/assets/72138672/212cf5c9-2bd5-475d-86b4-f0629efe95ff)
