### ISSUE TITLE
Writing test for Delete POI rouet

### ISSUE THREAD

**Issue by ali1373107** [TomStrong/DevOpsAssessment#65]

**Comment by TomStrong** [comment]
Delete POI Tests

- User should be able to delete their own POI (200)
- User should not be able to delete someone elses POI (404)
- User should not be able to delete non existent POI (404)
- User should not be able to delete POI by invalid ID (400)

- Admin should be able to delete any Users POI (200)
- Admin should not be able to delete another Admins POI (403)
- User should not be able to delete non existent POI (404)
- Admin should not be able to delete POI by invalid ID (400)
